[package]
name = "feather"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15"
poise = "0.6.1"
reqwest = "0.12.5"
serde = "1.0.203"
serde_json = "1.0.117"
flate2 = "1.0.30"
mongodb = "2.8.2"
